---
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
    Instance Profile and Logs stack for ELK Stacks
Parameters:
    SnapshotRepository:
        Description: S3 bucket name for elasticsearch snapshots repository
        Type: String
    MonitorStack:
        Description: >-
          Push logs from Elasticsearch, Nginx, KCL and CloudFormation to CloudWatch
          Logs
        Type: String
        Default: 'true'
        AllowedValues:
          - 'true'
          - 'false'

Conditions:
    HasS3: !Not [!Equals [!Ref SnapshotRepository,  '']]
    CreateCWLForStack: !Equals
      - !Ref MonitorStack
      - 'true'

Resources:
    ElasticsearchLogs:
        Type: 'AWS::Logs::LogGroup'
        Condition: CreateCWLForStack
    NginxAccessLogs:
        Type: 'AWS::Logs::LogGroup'
        Condition: CreateCWLForStack
    NginxErrorLogs:
        Type: 'AWS::Logs::LogGroup'
        Condition: CreateCWLForStack
    CloudFormationLogs:
        Type: 'AWS::Logs::LogGroup'
        Condition: CreateCWLForStack
    ElkS3Bucket:
        Type: AWS::S3::Bucket
        Condition: HasS3
        Properties:
            BucketName: !Ref SnapshotRepository
            AccessControl: Private
    LogstashCloudwatchPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: LogstashPolicy
            Groups: []
            Roles:
            - !Ref LogstashRole
            Users: []
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Action:
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
                Effect: Allow
                Resource: '*'
              - Action:
                - ec2:DescribeInstances
                Effect: Allow
                Resource: "*"
    ElkS3Policy:
        Type: AWS::IAM::Policy
        Condition: HasS3
        Properties:
            PolicyName: ElkS3Policy
            Groups: []
            Roles:
            - !Ref Role
            Users: []
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Action:
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${ElkS3Bucket}'
              - Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:AbortMultipartUpload
                - s3:ListMultipartUploadParts
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${ElkS3Bucket}/*'
    Role:
        Type: AWS::IAM::Role
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
              Statement:
              - Action: sts:AssumeRole
                Effect: Allow
                Principal:
                  Service:
                  - ec2.amazonaws.com
            Policies:
            - PolicyName: ec2-describe-instances
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Action: ec2:DescribeInstances
                  Effect: Allow
                  Resource: "*"

    LogstashRole:
        Type: AWS::IAM::Role
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
              Statement:
              - Action: sts:AssumeRole
                Effect: Allow
                Principal:
                  Service:
                  - ec2.amazonaws.com
            Policies:
            - PolicyName: ec2-describe-instances-logstash
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Action: ec2:DescribeInstances
                  Effect: Allow
                  Resource: "*"
    InstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: "/"
            Roles:
            - !Ref Role
    LogstashInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: "/"
            Roles:
            - !Ref LogstashRole
Outputs:
    InstanceProfile:
        Value: !Ref InstanceProfile
        Description: Instance Profile for Elastic Search
    LogstashInstanceProfile:
        Value: !Ref LogstashInstanceProfile
        Description: Instance Profile for Logstash
