filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /opt/aem/author/crx-quickstart/logs/project-spring*

  fields:
    env: test-6
    log_type: project-spring-error

  multiline.pattern: '^[0-9]{2}.[0-9]{2}.[0-9]{4}'

    # Defines if the pattern set under pattern should be negated or not. Default is false.
  multiline.negate: true

    # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
    # that was (not) matched before or after or as long as a pattern is not matched based on negate.
    # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  multiline.match: before

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /opt/aem/author/crx-quickstart/logs/error*

  fields:
    env: test-6
    log_type: cq-error

  multiline.pattern: '^[0-9]{2}.[0-9]{2}.[0-9]{4}'

    # Defines if the pattern set under pattern should be negated or not. Default is false.
  multiline.negate: true

    # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
    # that was (not) matched before or after or as long as a pattern is not matched based on negate.
    # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  multiline.match: after